# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=400)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=300)),
                ('photo', models.FileField(upload_to='')),
                ('additional_info', models.CharField(default='', max_length=2000)),
                ('contest_pic', models.FileField(upload_to='')),
                ('likes_count', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likers_id', models.IntegerField(max_length=1000)),
                ('pic_id', models.IntegerField(max_length=1000)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
