# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='likes_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='likers_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='pic_id',
            field=models.IntegerField(),
        ),
    ]
