# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0002_auto_20160614_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=300)),
                ('photo', models.FileField(upload_to='')),
                ('additional_info', models.CharField(default='', max_length=2000)),
                ('contest_pic', models.FileField(upload_to='')),
                ('likes_count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='contest_pic',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='photo',
        ),
    ]
