# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0003_auto_20160614_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
