# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0004_profile_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='password',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='username',
        ),
        migrations.AddField(
            model_name='accounts',
            name='additional_info',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='accounts',
            name='contest_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='accounts',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='accounts',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='accounts',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
